services:
  backend:
    build: ./backend
    ports:
      - "3008:3008"
    env_file:
      - backend/.env

  frontend:
    build: ./palatable-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend